name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      
      - name: Install git-chglog
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
      
      - name: Create changelog
        run: |
          git-chglog -o CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore(changelog): update changelog"
          git push